name: thungthung
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  go_router: ^14.8.0
  flutter_profile_picture: ^2.0.0
  lottie: ^3.3.1
  animated_splash_screen: ^1.3.0
  get: ^4.7.2
  provider: ^6.1.2
  shared_preferences: ^2.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:

    - assets/product/
    - assets/lottie/

    - assets/app_logo/logo.png
    - assets/app_logo/logo1.png
    - assets/app_logo/logo2.png
    - assets/app_logo/logo3.png
    - assets/app_logo/logo4.png

    - assets/bill_board/1.png
    - assets/bill_board/2.png
    - assets/bill_board/3.png
    - assets/bill_board/4.png

    - assets/band_logo/social.png
    - assets/band_logo/apple.png
    - assets/band_logo/search.png
    - assets/band_logo/social.png

    - assets/payment/Cash.png
    - assets/payment/PromptPay-logo.png
    - assets/payment/qrcode.png
    - assets/payment/truemoney.png
    - assets/payment/creditcard.png

    


