// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt8PbpTUMWMZACoh9STqpIqH9YRlabnqc',
    appId: '1:425380551428:web:c54300270d1c35d6edce51',
    messagingSenderId: '425380551428',
    projectId: 'thungthung-c21fe',
    authDomain: 'thungthung-c21fe.firebaseapp.com',
    storageBucket: 'thungthung-c21fe.firebasestorage.app',
    measurementId: 'G-RG29FSMBQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCANLxKEXM-2UnXRoeGjOVsvtFCxPrB6Eg',
    appId: '1:425380551428:android:3f682bd926d0980dedce51',
    messagingSenderId: '425380551428',
    projectId: 'thungthung-c21fe',
    storageBucket: 'thungthung-c21fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9J6ky4piATrAfTioKfqMQUNJfM4A9Zg',
    appId: '1:425380551428:ios:7ef11ee1a369a59cedce51',
    messagingSenderId: '425380551428',
    projectId: 'thungthung-c21fe',
    storageBucket: 'thungthung-c21fe.firebasestorage.app',
    iosBundleId: 'com.thungthung.thungthung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt8PbpTUMWMZACoh9STqpIqH9YRlabnqc',
    appId: '1:425380551428:web:aac980e82da20e4dedce51',
    messagingSenderId: '425380551428',
    projectId: 'thungthung-c21fe',
    authDomain: 'thungthung-c21fe.firebaseapp.com',
    storageBucket: 'thungthung-c21fe.firebasestorage.app',
    measurementId: 'G-YYLE0PFHHB',
  );
}
